version: '3.4'

services:
  db:
    container_name: db
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
    ports:
      - 1433:1433

  sudokubackend:
    image: ${DOCKER_REGISTRY-}sudokubackend
    build:
      context: .
      dockerfile: Dockerfile
    
    
